# Generated by Django 3.2 on 2022-06-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MOVIE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('ALIAS', models.CharField(blank=True, max_length=255, null=True)),
                ('ACTORS', models.CharField(blank=True, max_length=255, null=True)),
                ('COVER', models.CharField(blank=True, max_length=255, null=True)),
                ('DIRECTORS', models.CharField(blank=True, max_length=255, null=True)),
                ('DOUBAN_SCORE', models.CharField(blank=True, max_length=255, null=True)),
                ('DOUBAN_VOTES', models.CharField(blank=True, max_length=255, null=True)),
                ('GENRES', models.CharField(blank=True, max_length=255, null=True)),
                ('IMDB_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('LANGUAGES', models.CharField(blank=True, max_length=255, null=True)),
                ('MINS', models.CharField(blank=True, max_length=255, null=True)),
                ('OFFICIAL_SITE', models.CharField(blank=True, max_length=255, null=True)),
                ('REGIONS', models.CharField(blank=True, max_length=255, null=True)),
                ('RELEASE_DATE', models.CharField(blank=True, max_length=255, null=True)),
                ('SLUG', models.CharField(blank=True, max_length=255, null=True)),
                ('STORYLINE', models.TextField(blank=True, null=True)),
                ('TAGS', models.CharField(blank=True, max_length=255, null=True)),
                ('YEAR', models.CharField(blank=True, max_length=255, null=True)),
                ('ACTOR_IDS', models.CharField(blank=True, max_length=255, null=True)),
                ('DIRECTOR_IDS', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='popular_movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('moive_id', models.IntegerField(default=20, verbose_name='电影ID')),
                ('name', models.CharField(max_length=128)),
                ('moive_url', models.CharField(max_length=128)),
                ('photo_url', models.CharField(max_length=128)),
                ('rating', models.FloatField(default=0, verbose_name='电影评分')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128)),
                ('user_password', models.IntegerField(default=20, verbose_name='密码')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
