# Generated by Django 3.2 on 2022-07-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0002_auto_20220701_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commendts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COMMENT_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('USER_MD5', models.CharField(blank=True, max_length=255, null=True)),
                ('MOVIE_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('CONTENT', models.TextField(blank=True, max_length=255, null=True)),
                ('VOTES', models.CharField(blank=True, max_length=255, null=True)),
                ('COMMENT_TIME', models.CharField(blank=True, max_length=255, null=True)),
                ('RATING', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_evaluate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('MOVIE_NAME', models.CharField(blank=True, max_length=255, null=True)),
                ('SCORE', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
