# Generated by Django 3.2 on 2022-07-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_commendts_user_evaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_evaluate',
            name='MOVIE_ID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
